### ISSUE TITLE
Fix up favicon on CodeForABQ.org

### ISSUE THREAD

**Issue by bradweikel** [codeforabq/Brigade-Brain#1]
This site thoroughly dismantles our favicon:
http://realfavicongenerator.net/favicon_checker?site=codeforabq.org#.VgL4qY9VhBe

Most notably, the current favicon is a PNG rather than an ICO. PNG favicons aren't yet universally supported, plus it's better to supply multiple resolutions.

In addition, the Wordpress theme seems to have thrown in some random apple touch icons, which need to be replaced and rounded out with more variations.

**Comment by Smallmelo** [comment]
Used this as an excuse to transfer the StyleGuide folder from Google Drive to the Brain.  One folder down, too many to go. 

<a href="https://github.com/codeforabq/Brigade-Brain/tree/master/StyleGuide"> Code for ABQ Style Guide Files</a>

**Comment by bradweikel** [comment]
Fixed in codeforabq/codeforabq.github.io@fcf3e0ccfcfbdc938dd338a068bf4d5eb3d5349e . Will be applied when we switch over to Github Pages hosting.
