### ISSUE TITLE
codeforabq.org website source repo?

### ISSUE THREAD

**Issue by webmaven** [codeforabq/Brigade-Brain#10]
Where is the version control repo for the codeforabq.org website?

**Comment by bradweikel** [comment]
There isn't one, at the moment. 

It's a wordpress site with hosting paid through next summer, but sometime in 2016 I was thinking I'd move it to GitHub pages so it's free to host and easier for people to contribute. 

For the time being, though, just file issues/suggestions in this repo.

**Comment by webmaven** [comment]
:+1:

**Comment by bradweikel** [comment]
Ignore me. Just testing slack integration. Do comments on closed issues get posted?
