### ISSUE TITLE
change the redirect link on the menu for donate

### ISSUE THREAD

**Issue by Smallmelo** [codeforabq/Brigade-Brain#12]
code for america changed their donate page.  change the redirect link on the top menu for the "donate" button to:
https://secure.codeforamerica.org/page/contribute/?brigade=Code%20for%20ABQ

**Comment by bradweikel** [comment]
I've made this change in the cloned version I'm making with github pages
https://github.com/codeforabq/codeforabq.github.io/commit/cee7a124ebbae407029244a65e391df1a58532a4
