### ISSUE TITLE
Cleanup old "code4abq" references.

### ISSUE THREAD

**Issue by bradweikel** [codeforabq/Brigade-Brain#2]
Before we rebranded, I believe [this repository](https://github.com/codeforabq/code4abq.github.io) was being served as code4abq.github.io .

Now that's broken (it doesn't work as codeforabq.github.io either), and there's a seemingly rogue "application" in our github org settings ([admin link](https://github.com/organizations/codeforabq/settings/applications)). Does this application serve some purpose? Am I correct in remembering that it's related to these *.github.io urls? Or was it just a 

In addition, in this Brigade Brain repo there's a "projects.html" file that seems to be pursuing a similar goal of being a github-centric landing page for the brigade, but it's 

All of this seems pretty muddled and next steps aren't clear, so *let's decide what we actually want and clean up the old cruft*.

My proposed next steps:
1) Decide whether we want anything at codeforabq.github.io.
2) Delete code4abq.github.io (or rename it codeforabq.github.io if we want to use that)
3) Delete the dated application from our org settings. If we need one again, we'll recreate it.
4) Get clarify on the projects.html file in this repo, and delete it if it's not needed.

**Comment by Smallmelo** [comment]
1) I don't see a purpose.  Hold off on creating for now.
2) Deleted.
3) Deleted.
4) Deleted.  Serves no purpose.

**Comment by bradweikel** [comment]
Thx! Closing issue.
