### ISSUE TITLE
Add feature projects to home page

### ISSUE THREAD

**Issue by Smallmelo** [codeforabq/Brigade-Brain#3]
Add a fourth column to the "Get Involved!" section of the home page template called “Featured Project” with pointers to both the abqvotes.org and imagineabq.org.  If you want to use fancy logos instead of regular text point to the sites:

https://github.com/codeforabq/abqvotes/blob/master/images/abqvotes_logo.png
https://github.com/codeforabq/imagine-abq/blob/master/Logos/imagine-banner-black.png

**Comment by bradweikel** [comment]
Copied this over to the website's repo. Closing this one.
